apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocddeploymnt
spec:
  selector:
    matchLabels:
      app: argocdone
  replicas: 2
  template:
    metadata:
      labels:
        app: argocdone
    spec:
      containers:
        - name: argocdcon
          image: nginx:3
          ports:
          - containerPort: 8080
